-- Weapon catalog derived from ox_inventory/es_extended data.
-- Component sets are deduplicated to keep the public source readable.

local componentSets = {
    [1] = { 'at_flashlight', 'at_suppressor_light', 'at_clip_extended_pistol', 'at_skin_metal' },
    [2] = { 'at_flashlight', 'at_suppressor_light', 'at_clip_extended_pistol', 'at_skin_luxe' },
    [3] = { 'at_flashlight', 'at_suppressor_light', 'at_clip_extended_pistol', 'at_skin_wood' },
    [4] = { 'at_flashlight', 'at_suppressor_heavy', 'at_clip_extended_pistol', 'at_skin_pearl' },
    [5] = { 'at_flashlight', 'at_suppressor_light', 'at_clip_extended_pistol', 'at_compensator', 'at_scope_holo', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [6] = { 'at_skin_vip', 'at_skin_bodyguard' },
    [7] = { 'at_flashlight', 'at_compensator', 'at_scope_macro', 'at_scope_holo', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [8] = { 'at_clip_extended_pistol', 'at_skin_wood' },
    [9] = { 'at_suppressor_light', 'at_clip_extended_pistol' },
    [10] = { 'at_suppressor_light' },
    [11] = { 'at_flashlight', 'at_suppressor_heavy', 'at_clip_extended_smg', 'at_scope_macro', 'at_skin_luxe' },
    [12] = { 'at_grip', 'at_clip_extended_mg', 'at_scope_medium' },
    [13] = { 'at_grip', 'at_barrel', 'at_clip_extended_mg', 'at_scope_small', 'at_scope_medium', 'at_scope_holo', 'at_muzzle_flat', 'at_muzzle_tactical', 'at_muzzle_fat', 'at_muzzle_precision', 'at_muzzle_heavy', 'at_muzzle_slanted', 'at_muzzle_split', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [14] = { 'at_flashlight', 'at_grip', 'at_clip_extended_smg', 'at_clip_drum_smg', 'at_scope_small' },
    [15] = { 'at_clip_extended_mg' },
    [16] = { 'at_clip_extended_mg', 'at_scope_small', 'at_skin_luxe' },
    [17] = { 'at_suppressor_light', 'at_clip_extended_smg', 'at_clip_drum_smg' },
    [18] = { 'at_clip_extended_smg' },
    [19] = { 'at_flashlight', 'at_suppressor_light', 'at_clip_extended_smg', 'at_clip_drum_smg', 'at_scope_macro', 'at_skin_luxe' },
    [20] = { 'at_flashlight', 'at_suppressor_light', 'at_barrel', 'at_clip_extended_smg', 'at_scope_macro', 'at_scope_small', 'at_scope_holo', 'at_muzzle_flat', 'at_muzzle_tactical', 'at_muzzle_fat', 'at_muzzle_precision', 'at_muzzle_heavy', 'at_muzzle_slanted', 'at_muzzle_split', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [21] = { 'at_suppressor_heavy', 'at_clip_extended_pistol', 'at_scope_macro' },
    [22] = { 'at_flashlight', 'at_suppressor_heavy', 'at_clip_extended_rifle', 'at_scope_small', 'at_skin_metal' },
    [23] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_rifle', 'at_clip_drum_rifle', 'at_scope_macro', 'at_skin_luxe' },
    [24] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_barrel', 'at_clip_extended_rifle', 'at_scope_macro', 'at_scope_medium', 'at_scope_holo', 'at_muzzle_flat', 'at_muzzle_tactical', 'at_muzzle_fat', 'at_muzzle_precision', 'at_muzzle_heavy', 'at_muzzle_slanted', 'at_muzzle_split', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [25] = { 'at_suppressor_heavy', 'at_clip_extended_rifle' },
    [26] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_rifle', 'at_scope_small', 'at_skin_metal' },
    [27] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_barrel', 'at_clip_extended_rifle', 'at_scope_macro', 'at_scope_small', 'at_scope_holo', 'at_muzzle_flat', 'at_muzzle_tactical', 'at_muzzle_fat', 'at_muzzle_precision', 'at_muzzle_heavy', 'at_muzzle_slanted', 'at_muzzle_split', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [28] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_rifle', 'at_clip_drum_rifle', 'at_scope_medium', 'at_skin_luxe' },
    [29] = { 'at_clip_extended_rifle', 'at_clip_drum_rifle' },
    [30] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_rifle', 'at_scope_medium' },
    [31] = { 'at_flashlight', 'at_suppressor_heavy', 'at_clip_extended_rifle', 'at_scope_small' },
    [32] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_rifle', 'at_clip_drum_rifle', 'at_scope_medium', 'at_skin_metal' },
    [33] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_rifle' },
    [34] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_shotgun' },
    [35] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip' },
    [36] = { 'at_flashlight', 'at_suppressor_heavy' },
    [37] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_shotgun', 'at_clip_drum_shotgun' },
    [38] = { 'at_flashlight', 'at_suppressor_heavy', 'at_skin_luxe' },
    [39] = { 'at_flashlight', 'at_suppressor_heavy', 'at_scope_macro', 'at_scope_small', 'at_scope_holo', 'at_muzzle_squared', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [40] = { 'at_skin_metal' },
    [41] = { 'at_scope_advanced' },
    [42] = { 'at_suppressor_heavy', 'at_barrel', 'at_clip_extended_sniper', 'at_scope_large', 'at_scope_advanced', 'at_scope_nv', 'at_scope_thermal', 'at_muzzle_squared', 'at_muzzle_bell', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [43] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_clip_extended_sniper', 'at_skin_luxe' },
    [44] = { 'at_flashlight', 'at_suppressor_heavy', 'at_grip', 'at_barrel', 'at_clip_extended_sniper', 'at_scope_medium', 'at_scope_holo', 'at_muzzle_flat', 'at_muzzle_tactical', 'at_muzzle_fat', 'at_muzzle_precision', 'at_muzzle_heavy', 'at_muzzle_slanted', 'at_muzzle_split', 'at_skin_camo', 'at_skin_brushstroke', 'at_skin_woodland', 'at_skin_skull', 'at_skin_sessanta', 'at_skin_perseus', 'at_skin_leopard', 'at_skin_zebra', 'at_skin_geometric', 'at_skin_boom', 'at_skin_patriotic' },
    [45] = { 'at_suppressor_heavy', 'at_scope_advanced', 'at_skin_wood' },
    [46] = { 'at_skin_ballas', 'at_skin_diamond', 'at_skin_dollar', 'at_skin_hate', 'at_skin_king', 'at_skin_love', 'at_skin_pimp', 'at_skin_player', 'at_skin_vagos' },
}

local weaponRows = {
    { 'WEAPON_APPISTOL', 'AP Pistol', 'handguns', 'ammo-9', false, 1 },
    { 'WEAPON_CERAMICPISTOL', 'Ceramic Pistol', 'handguns', 'ammo-9', false, 0 },
    { 'WEAPON_COMBATPISTOL', 'Combat Pistol', 'handguns', 'ammo-9', false, 2 },
    { 'WEAPON_DOUBLEACTION', 'Double Action Revolver', 'handguns', 'ammo-38', false, 0 },
    { 'WEAPON_FLAREGUN', 'Flare Gun', 'handguns', 'ammo-flare', false, 0 },
    { 'WEAPON_HEAVYPISTOL', 'Heavy Pistol', 'handguns', 'ammo-45', false, 3 },
    { 'WEAPON_MARKSMANPISTOL', 'Marksman Pistol', 'handguns', 'ammo-22', false, 0 },
    { 'WEAPON_NAVYREVOLVER', 'Navy Revolver', 'handguns', 'ammo-44', false, 0 },
    { 'WEAPON_GADGETPISTOL', 'Perico Pistol', 'handguns', 'ammo-9', false, 0 },
    { 'WEAPON_PISTOL', 'Pistol', 'handguns', 'ammo-9', false, 2 },
    { 'WEAPON_PISTOL50', 'Pistol .50', 'handguns', 'ammo-50', false, 4 },
    { 'WEAPON_PISTOL_MK2', 'Pistol MK2', 'handguns', 'ammo-9', false, 5 },
    { 'WEAPON_REVOLVER', 'Revolver', 'handguns', 'ammo-44', false, 6 },
    { 'WEAPON_REVOLVER_MK2', 'Revolver MK2', 'handguns', 'ammo-44', false, 7 },
    { 'WEAPON_SNSPISTOL', 'SNS Pistol', 'handguns', 'ammo-45', false, 8 },
    { 'WEAPON_SNSPISTOL_MK2', 'SNS Pistol MK2', 'handguns', 'ammo-45', false, 5 },
    { 'WEAPON_STUNGUN', 'Tazer', 'handguns', nil, false, 0 },
    { 'WEAPON_RAYPISTOL', 'Up-n-Atomizer', 'handguns', nil, false, 0 },
    { 'WEAPON_VINTAGEPISTOL', 'Vintage Pistol', 'handguns', 'ammo-9', false, 9 },
    { 'WEAPON_PISTOLXM3', 'WM 29 Pistol', 'handguns', 'ammo-9', false, 10 },
    { 'WEAPON_ASSAULTSMG', 'Assault SMG', 'smg_lmg', 'ammo-rifle', false, 11 },
    { 'WEAPON_COMBATMG', 'Combat MG', 'smg_lmg', 'ammo-rifle', false, 12 },
    { 'WEAPON_COMBATMG_MK2', 'Combat MG MK2', 'smg_lmg', 'ammo-rifle2', false, 13 },
    { 'WEAPON_COMBATPDW', 'Combat PDW', 'smg_lmg', 'ammo-9', false, 14 },
    { 'WEAPON_GUSENBERG', 'Gusenberg', 'smg_lmg', 'ammo-45', false, 15 },
    { 'WEAPON_MG', 'Machine Gun', 'smg_lmg', 'ammo-rifle2', false, 16 },
    { 'WEAPON_MACHINEPISTOL', 'Machine Pistol', 'smg_lmg', 'ammo-9', false, 17 },
    { 'WEAPON_MICROSMG', 'Micro SMG', 'smg_lmg', 'ammo-45', false, 11 },
    { 'WEAPON_MINISMG', 'Mini SMG', 'smg_lmg', 'ammo-9', false, 18 },
    { 'WEAPON_SMG', 'SMG', 'smg_lmg', 'ammo-9', false, 19 },
    { 'WEAPON_SMG_MK2', 'SMG Mk2', 'smg_lmg', 'ammo-9', false, 20 },
    { 'WEAPON_TECPISTOL', 'Tactical SMG', 'smg_lmg', 'ammo-9', false, 21 },
    { 'WEAPON_RAYCARBINE', 'Unholy Hellbringer', 'smg_lmg', 'ammo-laser', false, 0 },
    { 'WEAPON_ADVANCEDRIFLE', 'Advanced Rifle', 'rifles', 'ammo-rifle', false, 22 },
    { 'WEAPON_ASSAULTRIFLE', 'Assault Rifle', 'rifles', 'ammo-rifle2', false, 23 },
    { 'WEAPON_ASSAULTRIFLE_MK2', 'Assault Rifle MK2', 'rifles', 'ammo-rifle2', false, 24 },
    { 'WEAPON_BATTLERIFLE', 'Battle Rifle', 'rifles', 'ammo-rifle2', false, 25 },
    { 'WEAPON_BULLPUPRIFLE', 'Bullpup Rifle', 'rifles', 'ammo-rifle', false, 26 },
    { 'WEAPON_BULLPUPRIFLE_MK2', 'Bullpup Rifle MK2', 'rifles', 'ammo-rifle', false, 27 },
    { 'WEAPON_CARBINERIFLE', 'Carbine Rifle', 'rifles', 'ammo-rifle', false, 28 },
    { 'WEAPON_CARBINERIFLE_MK2', 'Carbine Rifle MK2', 'rifles', 'ammo-rifle', false, 24 },
    { 'WEAPON_COMPACTRIFLE', 'Compact Rifle', 'rifles', 'ammo-rifle2', false, 29 },
    { 'WEAPON_HEAVYRIFLE', 'Heavy Rifle', 'rifles', 'ammo-rifle', false, 30 },
    { 'WEAPON_MILITARYRIFLE', 'Military Rifle', 'rifles', 'ammo-rifle', false, 31 },
    { 'WEAPON_SPECIALCARBINE', 'Special Carbine', 'rifles', 'ammo-rifle', false, 32 },
    { 'WEAPON_SPECIALCARBINE_MK2', 'Special Carbine MK2', 'rifles', 'ammo-rifle', false, 24 },
    { 'WEAPON_TACTICALRIFLE', 'Tactical Rifle', 'rifles', 'ammo-rifle', false, 33 },
    { 'WEAPON_ASSAULTSHOTGUN', 'Assault Shotgun', 'shotguns', 'ammo-shotgun', false, 34 },
    { 'WEAPON_BULLPUPSHOTGUN', 'Bullpup Shotgun', 'shotguns', 'ammo-shotgun', false, 35 },
    { 'WEAPON_COMBATSHOTGUN', 'Combat Shotgun', 'shotguns', 'ammo-shotgun', false, 36 },
    { 'WEAPON_DBSHOTGUN', 'Double Barrel Shotgun', 'shotguns', 'ammo-shotgun', false, 0 },
    { 'WEAPON_HEAVYSHOTGUN', 'Heavy Shotgun', 'shotguns', 'ammo-shotgun', false, 37 },
    { 'WEAPON_MUSKET', 'Musket', 'shotguns', 'ammo-musket', false, 0 },
    { 'WEAPON_PUMPSHOTGUN', 'Pump Shotgun', 'shotguns', 'ammo-shotgun', false, 38 },
    { 'WEAPON_PUMPSHOTGUN_MK2', 'Pump Shotgun MK2', 'shotguns', 'ammo-shotgun', false, 39 },
    { 'WEAPON_SAWNOFFSHOTGUN', 'Sawn Off Shotgun', 'shotguns', 'ammo-shotgun', false, 40 },
    { 'WEAPON_AUTOSHOTGUN', 'Sweeper Shotgun', 'shotguns', 'ammo-shotgun', false, 0 },
    { 'WEAPON_HEAVYSNIPER', 'Heavy Sniper', 'sniper', 'ammo-heavysniper', false, 41 },
    { 'WEAPON_HEAVYSNIPER_MK2', 'Heavy Sniper MK2', 'sniper', 'ammo-heavysniper', false, 42 },
    { 'WEAPON_MARKSMANRIFLE', 'Marksman Rifle', 'sniper', 'ammo-sniper', false, 43 },
    { 'WEAPON_MARKSMANRIFLE_MK2', 'Marksman Rifle MK2', 'sniper', 'ammo-sniper', false, 44 },
    { 'WEAPON_PRECISIONRIFLE', 'Precision Rifle', 'sniper', 'ammo-sniper', false, 0 },
    { 'WEAPON_SNIPERRIFLE', 'Sniper Rifle', 'sniper', 'ammo-sniper', false, 45 },
    { 'WEAPON_EMPLAUNCHER', 'Compact EMP Launcher', 'heavy', 'ammo-emp', false, 0 },
    { 'WEAPON_COMPACTLAUNCHER', 'Compact Grenade Launcher', 'heavy', 'ammo-grenade', false, 0 },
    { 'WEAPON_GRENADELAUNCHER', 'Grenade Launcher', 'heavy', 'ammo-grenade', false, 0 },
    { 'WEAPON_HOMINGLAUNCHER', 'Homing Launcher', 'heavy', 'ammo-rocket', false, 0 },
    { 'WEAPON_MINIGUN', 'Minigun', 'heavy', 'ammo-rifle2', false, 0 },
    { 'WEAPON_RAILGUN', 'Railgun', 'heavy', 'ammo-railgun', false, 0 },
    { 'WEAPON_RAILGUNXM3', 'Railgun XM3', 'heavy', 'ammo-railgun', false, 0 },
    { 'WEAPON_RPG', 'RPG', 'heavy', 'ammo-rocket', false, 0 },
    { 'WEAPON_SNOWLAUNCHER', 'Snowball Launcher', 'heavy', 'WEAPON_SNOWBALL', false, 0 },
    { 'WEAPON_RAYMINIGUN', 'Widowmaker', 'heavy', 'ammo-laser', false, 0 },
    { 'WEAPON_BAT', 'Bat', 'melee', nil, false, 0 },
    { 'WEAPON_BATTLEAXE', 'Battle Axe', 'melee', nil, false, 0 },
    { 'WEAPON_BOTTLE', 'Bottle', 'melee', nil, false, 0 },
    { 'WEAPON_CANDYCANE', 'Candy Cane', 'melee', nil, false, 0 },
    { 'WEAPON_CROWBAR', 'Crowbar', 'melee', nil, false, 0 },
    { 'WEAPON_DAGGER', 'Dagger', 'melee', nil, false, 0 },
    { 'WEAPON_FLASHLIGHT', 'Flashlight', 'melee', nil, false, 0 },
    { 'WEAPON_GOLFCLUB', 'Golf Club', 'melee', nil, false, 0 },
    { 'WEAPON_HAMMER', 'Hammer', 'melee', nil, false, 0 },
    { 'WEAPON_HATCHET', 'Hatchet', 'melee', nil, false, 0 },
    { 'WEAPON_KNIFE', 'Knife', 'melee', nil, false, 0 },
    { 'WEAPON_KNUCKLE', 'Knuckle Dusters', 'melee', nil, false, 46 },
    { 'WEAPON_MACHETE', 'Machete', 'melee', nil, false, 0 },
    { 'WEAPON_NIGHTSTICK', 'Nightstick', 'melee', nil, false, 0 },
    { 'WEAPON_POOLCUE', 'Pool Cue', 'melee', nil, false, 0 },
    { 'WEAPON_STONE_HATCHET', 'Stone Hatchet', 'melee', nil, false, 0 },
    { 'WEAPON_SWITCHBLADE', 'Switchblade', 'melee', nil, false, 6 },
    { 'WEAPON_WRENCH', 'Wrench', 'melee', nil, false, 0 },
    { 'WEAPON_BALL', 'Ball', 'thrown', nil, true, 0 },
    { 'WEAPON_BZGAS', 'BZ Gas', 'thrown', nil, true, 0 },
    { 'WEAPON_FERTILIZERCAN', 'Fertilizer Can', 'thrown', nil, false, 0 },
    { 'WEAPON_FIREWORK', 'Firework Launcher', 'thrown', 'ammo-firework', false, 0 },
    { 'WEAPON_FLARE', 'Flare', 'thrown', nil, true, 0 },
    { 'WEAPON_GRENADE', 'Grenade', 'thrown', nil, true, 0 },
    { 'WEAPON_HAZARDCAN', 'Hazard Can', 'thrown', nil, false, 0 },
    { 'WEAPON_PETROLCAN', 'Jerry Can', 'thrown', nil, false, 0 },
    { 'WEAPON_MOLOTOV', 'Molotov', 'thrown', nil, true, 0 },
    { 'WEAPON_PIPEBOMB', 'Pipe Bomb', 'thrown', nil, true, 0 },
    { 'WEAPON_PROXMINE', 'Proximity Mine', 'thrown', nil, true, 0 },
    { 'WEAPON_SMOKEGRENADE', 'Smoke Grenade', 'thrown', nil, true, 0 },
    { 'WEAPON_SNOWBALL', 'Snow Ball', 'thrown', nil, true, 0 },
    { 'WEAPON_STICKYBOMB', 'Sticky Bomb', 'thrown', nil, true, 0 },
    { 'WEAPON_TEARGAS', 'Tear Gas', 'thrown', nil, true, 0 },
    { 'WEAPON_FIREEXTINGUISHER', 'Fire Extinguisher', 'tools', nil, false, 0 },
    { 'WEAPON_METALDETECTOR', 'Metal Detector', 'tools', nil, false, 0 },
}

local weapons = {}
for i = 1, #weaponRows do
    local row = weaponRows[i]
    weapons[i] = {
        name = row[1], label = row[2], category = row[3], ammoname = row[4],
        throwable = row[5], components = componentSets[row[6]] or {},
    }
end

ArmasVipData = {
    categories = {
        { id = 'handguns', label = 'Pistolas', icon = 'Crosshair' },
        { id = 'smg_lmg', label = 'Subfusiles / Ametralladoras', icon = 'Zap' },
        { id = 'rifles', label = 'Rifles', icon = 'Target' },
        { id = 'shotguns', label = 'Escopetas', icon = 'Flame' },
        { id = 'sniper', label = 'Francotirador', icon = 'Scope' },
        { id = 'heavy', label = 'Pesadas', icon = 'Rocket' },
        { id = 'melee', label = 'Cuerpo a cuerpo', icon = 'Swords' },
        { id = 'thrown', label = 'Lanzables', icon = 'CircleDot' },
        { id = 'tools', label = 'Herramientas', icon = 'Wrench' },
    },
    weapons = weapons,
    components = {
        ['at_flashlight'] = { label = 'Tactical Flashlight', type = 'flashlight' },
        ['at_suppressor_light'] = { label = 'Suppressor', type = 'muzzle' },
        ['at_suppressor_heavy'] = { label = 'Tactical Suppressor', type = 'muzzle' },
        ['at_grip'] = { label = 'Grip', type = 'grip' },
        ['at_barrel'] = { label = 'Heavy Barrel', type = 'barrel' },
        ['at_clip_extended_pistol'] = { label = 'Extended Pistol Clip', type = 'magazine' },
        ['at_clip_extended_smg'] = { label = 'Extended SMG Clip', type = 'magazine' },
        ['at_clip_extended_shotgun'] = { label = 'Extended Shotgun Clip', type = 'magazine' },
        ['at_clip_extended_rifle'] = { label = 'Extended Rifle Clip', type = 'magazine' },
        ['at_clip_extended_mg'] = { label = 'Extended MG Clip', type = 'magazine' },
        ['at_clip_extended_sniper'] = { label = 'Extended Sniper Clip', type = 'magazine' },
        ['at_clip_drum_smg'] = { label = 'SMG Drum', type = 'magazine' },
        ['at_clip_drum_shotgun'] = { label = 'Shotgun Drum', type = 'magazine' },
        ['at_clip_drum_rifle'] = { label = 'Rifle Drum', type = 'magazine' },
        ['at_compensator'] = { label = 'Compensator', type = 'muzzle' },
        ['at_scope_macro'] = { label = 'Macro Scope', type = 'sight' },
        ['at_scope_small'] = { label = 'Small Scope', type = 'sight' },
        ['at_scope_medium'] = { label = 'Medium Scope', type = 'sight' },
        ['at_scope_large'] = { label = 'Large Scope', type = 'sight' },
        ['at_scope_advanced'] = { label = 'Advanced Scope', type = 'sight' },
        ['at_scope_nv'] = { label = 'NV Scope', type = 'sight' },
        ['at_scope_thermal'] = { label = 'Thermal Scope', type = 'sight' },
        ['at_scope_holo'] = { label = 'Holographic Sight', type = 'sight' },
        ['at_muzzle_flat'] = { label = 'Flat Muzzle', type = 'muzzle' },
        ['at_muzzle_tactical'] = { label = 'Tactical Muzzle', type = 'muzzle' },
        ['at_muzzle_fat'] = { label = 'Fat Muzzle', type = 'muzzle' },
        ['at_muzzle_precision'] = { label = 'Precision Muzzle', type = 'muzzle' },
        ['at_muzzle_heavy'] = { label = 'Heavy Muzzle', type = 'muzzle' },
        ['at_muzzle_slanted'] = { label = 'Slanted Muzzle', type = 'muzzle' },
        ['at_muzzle_split'] = { label = 'Split Muzzle', type = 'muzzle' },
        ['at_muzzle_squared'] = { label = 'Squared Muzzle', type = 'muzzle' },
        ['at_muzzle_bell'] = { label = 'Bell Muzzle', type = 'muzzle' },
        ['at_skin_luxe'] = { label = 'Luxury Weapon Kit', type = 'skin' },
        ['at_skin_wood'] = { label = 'Wood Weapon Kit', type = 'skin' },
        ['at_skin_metal'] = { label = 'Metal Weapon Kit', type = 'skin' },
        ['at_skin_pearl'] = { label = 'Pearl Weapon Kit', type = 'skin' },
        ['at_skin_ballas'] = { label = 'Ballas Weapon Kit', type = 'skin' },
        ['at_skin_diamond'] = { label = 'Diamond Weapon Kit', type = 'skin' },
        ['at_skin_dollar'] = { label = 'Dollar Weapon Kit', type = 'skin' },
        ['at_skin_hate'] = { label = 'Hate Weapon Kit', type = 'skin' },
        ['at_skin_king'] = { label = 'King Weapon Kit', type = 'skin' },
        ['at_skin_love'] = { label = 'Love Weapon Kit', type = 'skin' },
        ['at_skin_pimp'] = { label = 'Pimp Weapon Kit', type = 'skin' },
        ['at_skin_player'] = { label = 'Player Weapon Kit', type = 'skin' },
        ['at_skin_vagos'] = { label = 'Vagos Weapon Kit', type = 'skin' },
        ['at_skin_blagueurs'] = { label = 'Blagueurs Weapon Kit', type = 'skin' },
        ['at_skin_splatter'] = { label = 'Splatter Weapon Kit', type = 'skin' },
        ['at_skin_bulletholes'] = { label = 'Bullet Holes Weapon Kit', type = 'skin' },
        ['at_skin_burgershot'] = { label = 'Burger Shot Weapon Kit', type = 'skin' },
        ['at_skin_cluckinbell'] = { label = 'Cluckin Bell Weapon Kit', type = 'skin' },
        ['at_skin_fatalincursion'] = { label = 'Fatal Incursion Weapon Kit', type = 'skin' },
        ['at_skin_luchalibre'] = { label = 'Lucha Libre Weapon Kit', type = 'skin' },
        ['at_skin_trippy'] = { label = 'Trippy Weapon Kit', type = 'skin' },
        ['at_skin_tiedye'] = { label = 'Tie-Dye Weapon Kit', type = 'skin' },
        ['at_skin_wall'] = { label = 'Wall Weapon Kit', type = 'skin' },
        ['at_skin_vip'] = { label = 'VIP Weapon Kit', type = 'skin' },
        ['at_skin_bodyguard'] = { label = 'Bodyguard Weapon Kit', type = 'skin' },
        ['at_skin_festive'] = { label = 'Festive Weapon Kit', type = 'skin' },
        ['at_skin_security'] = { label = 'Security Weapon Kit', type = 'skin' },
        ['at_skin_camo'] = { label = 'Camo Weapon Kit', type = 'skin' },
        ['at_skin_brushstroke'] = { label = 'Brushstroke Weapon Kit', type = 'skin' },
        ['at_skin_woodland'] = { label = 'Woodland Weapon Kit', type = 'skin' },
        ['at_skin_skull'] = { label = 'Skull Weapon Kit', type = 'skin' },
        ['at_skin_sessanta'] = { label = 'Sessanta Weapon Kit', type = 'skin' },
        ['at_skin_perseus'] = { label = 'Perseus Weapon Kit', type = 'skin' },
        ['at_skin_leopard'] = { label = 'Leopard Weapon Kit', type = 'skin' },
        ['at_skin_zebra'] = { label = 'Zebra Weapon Kit', type = 'skin' },
        ['at_skin_geometric'] = { label = 'Geometric Weapon Kit', type = 'skin' },
        ['at_skin_boom'] = { label = 'Boom Weapon Kit', type = 'skin' },
        ['at_skin_patriotic'] = { label = 'Patriotic Weapon Kit', type = 'skin' },
    },
}
